/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.equiposControl;
import Controlador.jugadoresControlador;
import Modelos.Equipo;
import Modelos.Jugador;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Dan
 */
public class crearJugador extends javax.swing.JPanel {
    List <Equipo> equipos;
    Equipo team;
    Jugador player;
    /**
     * Creates new form crearJugador
     */
    public crearJugador() {
        initComponents();
        this.setSize(780, 350);
        equipo.addItem("seleccionar");
        this.cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        equipo = new java.awt.Choice();
        jButton1 = new javax.swing.JButton();
        nombre = new javax.swing.JTextField();
        cedula = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(700, 350));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("CREAR JUGADOR");

        jLabel2.setText("Nombre");

        jLabel3.setText("Cedula");

        jLabel4.setText("Equipo");

        equipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                equipoItemStateChanged(evt);
            }
        });
        equipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                equipoKeyTyped(evt);
            }
        });

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cedulaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(251, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombre)
                            .addComponent(equipo, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addGap(32, 32, 32)
                .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(equipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(jButton1)
                .addContainerGap(96, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // Crear Jugador
         try {
            jugadoresControlador jugadorControll = new jugadoresControlador();            
            
            int code = jugadorControll.addJugador(0, this.nombre.getText(), this.cedula.getText(), this.team.getNombre(), 0, 0 , 0);
            if (code == 0){
                JOptionPane.showMessageDialog(null, "Jugador agregado !!");
                this.nombre.setText("");
                this.cedula.setText("");
                equipo.select("seleccionar");
//                this.equipo.setSelectedItem("seleccionar");
//                this.codigo.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "Error Creando Jugador!");
            }
        }catch(Exception e){
            System.out.println("Error vista crear jugador : " + e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void equipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_equipoItemStateChanged
        // TODO add your handling code here:
        String[] parts = evt.getItem().toString().split("-");
        
        if (parts.length > 0) {            
            for(Equipo eq:equipos){
                if (eq.getId()  == Integer.parseInt(parts[0])) {
                    team = eq;                   
                }
            }
        }
    }//GEN-LAST:event_equipoItemStateChanged

    private void equipoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_equipoKeyTyped
        // TODO add your handling code here:
       
    }//GEN-LAST:event_equipoKeyTyped

    private void cedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cedulaKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();

        boolean numeros = key >= 48 && key <= 57;

        if (!numeros)
        {
            evt.consume();
        }

        if (this.cedula.getText().trim().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_cedulaKeyTyped

    public void cargarDatos(){
        equiposControl equipoController = new equiposControl();   
        equipos = equipoController.listEquipo();
        for(Equipo eq:equipos){
            equipo.addItem(eq.getId() + "- " + eq.getNombre());
        }

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cedula;
    private java.awt.Choice equipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
