/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.equiposControl;
import Modelos.Equipo;
import java.util.List;
import javax.swing.JOptionPane;


/**
 *
 * @author Dan
 */
public class eliminarEquipo extends javax.swing.JPanel {
    List <Equipo> equipos;
    Equipo team;
    /**
     * Creates new form eliminarJugador
     */
    public eliminarEquipo() {
        initComponents();
        
        equipo.addItem("seleccionar");
        equipo.addItem("test");
        this.cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        equipo = new java.awt.Choice();

        setPreferredSize(new java.awt.Dimension(700, 350));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("ELIMINAR EQUIPO");

        jLabel2.setText("Equipo");

        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        equipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                equipoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel2)
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(equipo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(equipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addComponent(jButton1)
                .addContainerGap(135, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void equipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_equipoItemStateChanged
        // TODO add your handling code here:
        System.out.println("preciono "+ evt.getItem());
        String[] parts = evt.getItem().toString().split("-");
        if (parts.length > 0) {            
            for(Equipo eq:equipos){
                if (eq.getId()  == Integer.parseInt(parts[0])) {
                    team = eq;                    
                }
            }
        }
    }//GEN-LAST:event_equipoItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try {
            equiposControl equipoController = new equiposControl();                        
            boolean code = equipoController.deleteEquipo(team);
            if (code){
                JOptionPane.showMessageDialog(null, "Equipo Eliminado!!");              
                this.equipo.select("Seleccionar");
//                this.codigo.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "Error Eliminando equipo!");
            }
        }catch(Exception e){
            System.out.println("Error " + e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    public void cargarDatos(){
        equiposControl equipoController = new equiposControl();   
        equipos = equipoController.listEquipo();
        for(Equipo eq:equipos){
            equipo.addItem(eq.getId() + "- " + eq.getNombre());
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice equipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
