package Modelos;
// Generated 28/06/2023 02:41:50 PM by Hibernate Tools 4.3.1



/**
 * Equipo generated by hbm2java
 */
public class Equipo  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String pais;
     private int codigo;
     private int puntos;
     private int partidosGanados;

    public Equipo() {
    }

    public Equipo(int id, String nombre, String pais, int codigo, int puntos, int partidosGanados) {
       this.id = id;
       this.nombre = nombre;
       this.pais = pais;
       this.codigo = codigo;
       this.puntos = puntos;
       this.partidosGanados = partidosGanados;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public int getPuntos() {
        return this.puntos;
    }
    
    public void setPuntos(int puntos) {
        this.puntos = puntos;
    }
    public int getPartidosGanados() {
        return this.partidosGanados;
    }
    
    public void setPartidosGanados(int partidosGanados) {
        this.partidosGanados = partidosGanados;
    }




}


