package Modelos;
// Generated 28/06/2023 02:41:50 PM by Hibernate Tools 4.3.1



/**
 * Jugador generated by hbm2java
 */
public class Jugador  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String cedula;
     private String equipo;
     private int numeroAmarillas;
     private int numeroRojas;
     private int numeroGoles;

   

    public Jugador() { // int id, String nombre, String cedula, String equipo, int numeroAmarillas, int numeroRojas, int numeroGoles
//       this.id = id;
//       this.nombre = nombre;
//       this.cedula = cedula;
//       this.equipo = equipo;
//       this.numeroAmarillas = numeroAmarillas;
//       this.numeroRojas = numeroRojas;
//       this.numeroGoles = numeroGoles;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    public String getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(String equipo) {
        this.equipo = equipo;
    }
    public int getNumeroAmarillas() {
        return this.numeroAmarillas;
    }
    
    public void setNumeroAmarillas(int numeroAmarillas) {
        this.numeroAmarillas = numeroAmarillas;
    }
    public int getNumeroRojas() {
        return this.numeroRojas;
    }
    
    public void setNumeroRojas(int numeroRojas) {
        this.numeroRojas = numeroRojas;
    }
    public int getNumeroGoles() {
        return this.numeroGoles;
    }
    
    public void setNumeroGoles(int numeroGoles) {
        this.numeroGoles = numeroGoles;
    }




}


