package Modelos;
// Generated 28/06/2023 02:41:50 PM by Hibernate Tools 4.3.1



/**
 * Partido generated by hbm2java
 */
public class Partido  implements java.io.Serializable {


     private int id;
     private String equipo1;
     private String equipo2;
     private int golesEquipo1;
     private int golesEquipo2;
     private int tarjetasRojasEquipo1;
     private int tarjetasRojasEquipo2;
     private int tarjetasAmarillasEquipo1;
     private int tarjetasAmarillasEquipo2;

    public Partido() {
    }

//    public Partido(int id, String equipo1, String equipo2, int golesEquipo1, int golesEquipo2, int tarjetasRojasEquipo1, int tarjetasRojasEquipo2, int tarjetasAmarillasEquipo1, int tarjetasAmarillasEquipo2) {
//       this.id = id;
//       this.equipo1 = equipo1;
//       this.equipo2 = equipo2;
//       this.golesEquipo1 = golesEquipo1;
//       this.golesEquipo2 = golesEquipo2;
//       this.tarjetasRojasEquipo1 = tarjetasRojasEquipo1;
//       this.tarjetasRojasEquipo2 = tarjetasRojasEquipo2;
//       this.tarjetasAmarillasEquipo1 = tarjetasAmarillasEquipo1;
//       this.tarjetasAmarillasEquipo2 = tarjetasAmarillasEquipo2;
//    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getEquipo1() {
        return this.equipo1;
    }
    
    public void setEquipo1(String equipo1) {
        this.equipo1 = equipo1;
    }
    public String getEquipo2() {
        return this.equipo2;
    }
    
    public void setEquipo2(String equipo2) {
        this.equipo2 = equipo2;
    }
    public int getGolesEquipo1() {
        return this.golesEquipo1;
    }
    
    public void setGolesEquipo1(int golesEquipo1) {
        this.golesEquipo1 = golesEquipo1;
    }
    public int getGolesEquipo2() {
        return this.golesEquipo2;
    }
    
    public void setGolesEquipo2(int golesEquipo2) {
        this.golesEquipo2 = golesEquipo2;
    }
    public int getTarjetasRojasEquipo1() {
        return this.tarjetasRojasEquipo1;
    }
    
    public void setTarjetasRojasEquipo1(int tarjetasRojasEquipo1) {
        this.tarjetasRojasEquipo1 = tarjetasRojasEquipo1;
    }
    public int getTarjetasRojasEquipo2() {
        return this.tarjetasRojasEquipo2;
    }
    
    public void setTarjetasRojasEquipo2(int tarjetasRojasEquipo2) {
        this.tarjetasRojasEquipo2 = tarjetasRojasEquipo2;
    }
    public int getTarjetasAmarillasEquipo1() {
        return this.tarjetasAmarillasEquipo1;
    }
    
    public void setTarjetasAmarillasEquipo1(int tarjetasAmarillasEquipo1) {
        this.tarjetasAmarillasEquipo1 = tarjetasAmarillasEquipo1;
    }
    public int getTarjetasAmarillasEquipo2() {
        return this.tarjetasAmarillasEquipo2;
    }
    
    public void setTarjetasAmarillasEquipo2(int tarjetasAmarillasEquipo2) {
        this.tarjetasAmarillasEquipo2 = tarjetasAmarillasEquipo2;
    }




}


